### ISSUE TITLE
Dual guide - extended read classification data

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/pycroquet#4]
Add an additional output file for `dual-guide` mode to be used in R&D investigations of libraries.

| read_seqs | hit_l | hit_r | hit_pair | count |
|:----------:|:----:|:----:|:--------:|:-----:|
| seq_l\|seq_r | U/M | U/M | Y/N | #number# |

(Note: later decided to standardise across all of the above the Y/N)

Where:

* read_seqs = `seq_l|seq_r`
    * reid pair sequence joined by `|`
* hit_l/r = `U/M` - Unmapped/Mapped:
    * mapped can indicate multiple matching guides, however they must have distinct sequences 
* hit_pair = `Y/N` - Yes/No
    * Hits a guide pair in expected orientation
* count = N
    * Number of read pairs of this exact sequence pair and orientation.

@vaofford can you confirm as expected please?

**Comment by vaofford** [comment]
Yes - so if I understand correctly, to search for reads matching to mismatched gene pairs I would be filtering this file for hit_l = M, hit_r = M, hit_pair = F? And then I'd be working out the mismatch guide/gene combination downstream of pyCROQUET?

**Comment by keiranmraine** [comment]
```python3
if hit_pair == "N" and hit_l == "M" and hit_r == "M":
   # investigate
```

and you can then potentially search out the read pairs from the CRAM which will list all the guide hits that are involved.

**Comment by keiranmraine** [comment]
Do you want all the the values as Y/N (yes/no) rather than a mix of Y/N and U/M (unmapped/mapped)?

**Comment by vaofford** [comment]
Can I see an example output?

From: Keiran Raine ***@***.***>
Reply to: cancerit/pycroquet ***@***.***>
Date: Wednesday, 24 November 2021 at 14:34
To: cancerit/pycroquet ***@***.***>
Cc: Victoria Offord ***@***.***>, Mention ***@***.***>
Subject: Re: [cancerit/pycroquet] Dual guide - extended read classification data (Issue #4) [EXT]


Do you want all the the values as Y/N (yes/no) rather than a mix of Y/N and U/M (unmapped/mapped)?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_pycroquet_issues_4-23issuecomment-2D977935985&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=WWDbtF7PL8T9mbXkxiDUVJADYa3iR0rVJKAN7vU2Sdk&m=Gjc9wuEIBez2glburCh1OCN193IWu4BWXs9OeJWyuNN3J_s9w8_3BNWEvgW4_hPa&s=9jTarXgem_lX3vIXD2ndVcc95hhE2ofYAudgArF5-qk&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFQYWPEIOE4CMADC44QBWJTUNTZXNANCNFSM5HYCWBDQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=WWDbtF7PL8T9mbXkxiDUVJADYa3iR0rVJKAN7vU2Sdk&m=Gjc9wuEIBez2glburCh1OCN193IWu4BWXs9OeJWyuNN3J_s9w8_3BNWEvgW4_hPa&s=CkjI-hrElY6dgh4YB1EUOWp6ij3OSxINN19xCpa2NTA&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=WWDbtF7PL8T9mbXkxiDUVJADYa3iR0rVJKAN7vU2Sdk&m=Gjc9wuEIBez2glburCh1OCN193IWu4BWXs9OeJWyuNN3J_s9w8_3BNWEvgW4_hPa&s=kt3YNWsujq9BFN0noYhB6m8GOVV2I91Q0GFah6XxkbM&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=WWDbtF7PL8T9mbXkxiDUVJADYa3iR0rVJKAN7vU2Sdk&m=Gjc9wuEIBez2glburCh1OCN193IWu4BWXs9OeJWyuNN3J_s9w8_3BNWEvgW4_hPa&s=so5ULyW8lWKX3e8KIYgh5AEHxzNLu_KAqB0Dvchjkjs&e=>.



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by keiranmraine** [comment]
I've not generated an output yet.

**Comment by keiranmraine** [comment]
> Can I see an example output?

```
$ zcat target.query_class.tsv.gz | head
#read_seqs      hit_l   hit_r   hit_pair        count
AAAAAAGCGGTCCTACACCA|CCTCGATCTTGTCGGCGCCC       N       N       N       1
AAAAAGAGAGTTGCATTCGA|AAGTGTACTACATAGAAAGC       N       N       N       1
AAAACAAAAGCAGATGACCG|TCTTGACGTGCTCCTGCCCA       N       N       N       1
AAAACCCTTACAGAAAATCT|CATCTTTCTGTATTTCGGCT       N       N       N       1
AAAACCCTTACAGAAAATCT|TCGCGTCCTCCTGGTCGACC       N       N       N       1
AAAAGAATCCAACGTGCAAG|CTGGTTTCTCTGGAAACCTC       N       N       N       1
AAAAGAATCCAACGTGCAAG|TCAGTAACTCCTTGGCGCGC       Y       N       N       1
...
TTGTGCCTGCCAGCTACAGG|CAGCTGTTTGATCTCATCGC       Y       Y       Y       1
TTTGAAAGGCTTCGAGGCAG|CTGAATCCCCGATCCAGAGA       Y       Y       Y       1
TTTGGCATACGGGTGAGTGG|TAGAGAAGTATCCAACCAGA       Y       Y       Y       1
```

**Comment by vaofford** [comment]
Yes please.

From: Keiran Raine ***@***.***>
Reply to: cancerit/pycroquet ***@***.***>
Date: Wednesday, 24 November 2021 at 16:14
To: cancerit/pycroquet ***@***.***>
Cc: Victoria Offord ***@***.***>, Mention ***@***.***>
Subject: Re: [cancerit/pycroquet] Dual guide - extended read classification data (Issue #4) [EXT]


Can I see an example output?

$ zcat target.query_class.tsv.gz | head

#read_seqs      hit_l   hit_r   hit_pair        count

AAAAAAGCGGTCCTACACCA|CCTCGATCTTGTCGGCGCCC       N       N       N       1

AAAAAGAGAGTTGCATTCGA|AAGTGTACTACATAGAAAGC       N       N       N       1

AAAACAAAAGCAGATGACCG|TCTTGACGTGCTCCTGCCCA       N       N       N       1

AAAACCCTTACAGAAAATCT|CATCTTTCTGTATTTCGGCT       N       N       N       1

AAAACCCTTACAGAAAATCT|TCGCGTCCTCCTGGTCGACC       N       N       N       1

AAAAGAATCCAACGTGCAAG|CTGGTTTCTCTGGAAACCTC       N       N       N       1

AAAAGAATCCAACGTGCAAG|TCAGTAACTCCTTGGCGCGC       Y       N       N       1

...

TTGTGCCTGCCAGCTACAGG|CAGCTGTTTGATCTCATCGC       Y       Y       Y       1

TTTGAAAGGCTTCGAGGCAG|CTGAATCCCCGATCCAGAGA       Y       Y       Y       1

TTTGGCATACGGGTGAGTGG|TAGAGAAGTATCCAACCAGA       Y       Y       Y       1

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cancerit_pycroquet_issues_4-23issuecomment-2D978023644&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=WWDbtF7PL8T9mbXkxiDUVJADYa3iR0rVJKAN7vU2Sdk&m=LRJZXdn9TScnQO7pR1OmmfeXIO76IxZdSqC24rmwdkihwIUjIxs5wI9zTG6oSUGa&s=MNeTADdru7_UGtEiz6cGMmb-QWL3tzz7Kat-bF_k8Qg&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFQYWPGG56M4ATVC4B4RULDUNUFNNANCNFSM5HYCWBDQ&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=WWDbtF7PL8T9mbXkxiDUVJADYa3iR0rVJKAN7vU2Sdk&m=LRJZXdn9TScnQO7pR1OmmfeXIO76IxZdSqC24rmwdkihwIUjIxs5wI9zTG6oSUGa&s=bRQ5pfLdUK8B0fHOXtgCwZrt-jVRpdAkEgjOpbmcOac&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=WWDbtF7PL8T9mbXkxiDUVJADYa3iR0rVJKAN7vU2Sdk&m=LRJZXdn9TScnQO7pR1OmmfeXIO76IxZdSqC24rmwdkihwIUjIxs5wI9zTG6oSUGa&s=rkAaWCHZPjCl67O2UnnCACc66JAImLedb4-nrGgkPVg&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=D7ByGjS34AllFgecYw0iC6Zq7qlm8uclZFI0SqQnqBo&r=WWDbtF7PL8T9mbXkxiDUVJADYa3iR0rVJKAN7vU2Sdk&m=LRJZXdn9TScnQO7pR1OmmfeXIO76IxZdSqC24rmwdkihwIUjIxs5wI9zTG6oSUGa&s=mnj8RLvLizN_74hvE_HUM7v4Z_LkWvnhMAjUu-XVI8Q&e=>.



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
